#!/bin/bash
# Example script to update arara
#
# *USAGE*
# Copy the file into your arara folder and make the file
# executable. 
#     chmod +x araraupdate
# Now you can run from the terminal
#     ./araraupdate
# 
# 

FILENAME=arara.jar 

echo -e "\tUpdate $FILENAME"


if [ -f $FILENAME ];
 then
   echo -e "\tOlder version of $FILENAME will be removed"
   rm -rf $FILENAME
   echo -e "\t$FILENAME will be downloaded to `pwd`"
   wget --no-check-certificate http://github.com/downloads/cereda/arara/arara.jar  
   echo -e "\tUpdate complete"
 else
   echo -e "\t$FILENAME not found -- no update possible"
   echo -e "\t$FILENAME will be downloaded to `pwd`"
   wget --no-check-certificate http://github.com/downloads/cereda/arara/arara.jar 
   echo -e "\tdownload complete"
fi

