# ------------------------------------------------------------
# Kotlin configuration
# ------------------------------------------------------------
kotlin.code.style=official
kotlin.daemon.jvm.options=-Xmx2g
kotlin.daemon.jvmargs=Xmx2g
# ------------------------------------------------------------
# Gradle configuration
# ------------------------------------------------------------
org.gradle.jvmargs=-XX:MaxMetaspaceSize=512m
# cache is currently disabled (see KT-79047)
# org.gradle.configuration-cache=true
# ------------------------------------------------------------
# Dokka configuration
# ------------------------------------------------------------
org.jetbrains.dokka.experimental.gradle.pluginMode.nowarn=true
# ------------------------------------------------------------
# Kotest configuration
# ------------------------------------------------------------
kotest.framework.classpath.scanning.autoscan.disable=true
# ------------------------------------------------------------
# arara configuration
# ------------------------------------------------------------
arara.jvm.target=11
arara.kotlin.api=2.2
arara.kotlin.language=2.2
